defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.13.2

version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Check lint
          command: yarn lint
      - run:
          name: Check test
          command: npm run test

  deploy_to_heroku:
      <<: *defaults
      steps:
        - checkout
        - heroku/deploy-via-git

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_to_heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - master  
